import { IContact } from '../../app/model/contact';

export const contacts: Array<IContact> = [
    {
        id: '99',
        firstName: 'Anish',
        lastName: 'Balmuchu',
        email: 'anishbalmuchu@gmail.com',
        phone: '7004992744',
        status: 'active',
    },
    {
        id: '88',
        firstName: 'Ankit',
        lastName: 'Ghosh',
        email: 'ankitghosh@gmail.com',
        phone: '7894561237',
        status: 'inactive',
    },
    {
        id: '77',
        firstName: 'Aman',
        lastName: 'Dev Burman',
        email: 'amanburman@gmail.com',
        phone: '9874563214',
        status: 'inactive',
    },
    {
        id: '66',
        firstName: 'Mano',
        lastName: 'Pan',
        email: 'manopan@gmail.com',
        phone: '7845123654',
        status: 'active',
    },
    {
        id: '55',
        firstName: 'Preetam',
        lastName: 'Kumar',
        email: 'preetamKumar@gmail.com',
        phone: '9568748596',
        status: 'inactive',
    },
    {
        id: '56',
        firstName: 'Anish',
        lastName: 'Balmuchu',
        email: 'anishbalmuchu@gmail.com',
        phone: '7004992744',
        status: 'inactive',
    },
    {
        id: '57',
        firstName: 'Ankit',
        lastName: 'Ghosh',
        email: 'ankitghosh@gmail.com',
        phone: '7894561237',
        status: 'active',
    },
    {
        id: '58',
        firstName: 'Aman',
        lastName: 'Dev Burman',
        email: 'amanburman@gmail.com',
        phone: '9874563214',
        status: 'active',
    },
    {
        id: '59',
        firstName: 'Mano',
        lastName: 'Pan',
        email: 'manopan@gmail.com',
        phone: '7845123654',
        status: 'inactive',
    },
    {
        id: '60',
        firstName: 'Preetam',
        lastName: 'Kumar',
        email: 'preetamKumar@gmail.com',
        phone: '9568748596',
        status: 'active',
    },
];
