export const contacts = [
    {
        id: '12',
        firstName: 'Anish',
        lastName: 'Balmuchu',
        email: 'anishbalmuchu@gmail.com',
        phone: '7004992744',
        status: 'active',
    },
    {
        id: '23',
        firstName: 'Ankit',
        lastName: 'Ghosh',
        email: 'ankitghosh@gmail.com',
        phone: '7894561237',
        status: 'inactive',
    },
    {
        id: '34',
        firstName: 'Aman',
        lastName: 'Dev Burman',
        email: 'amanburman@gmail.com',
        phone: '9874563214',
        status: 'inactive',
    },
    {
        id: '45',
        firstName: 'Mano',
        lastName: 'Pan',
        email: 'manopan@gmail.com',
        phone: '7845123654',
        status: 'active',
    },
    {
        id: '56',
        firstName: 'Preetam',
        lastName: 'Kumar',
        email: 'preetamKumar@gmail.com',
        phone: '9568748596',
        status: 'inactive',
    },
    {
        id: '67',
        firstName: 'Anish',
        lastName: 'Balmuchu',
        email: 'anishbalmuchu@gmail.com',
        phone: '7004992744',
        status: 'inactive',
    },
    {
        id: '78',
        firstName: 'Ankit',
        lastName: 'Ghosh',
        email: 'ankitghosh@gmail.com',
        phone: '7894561237',
        status: 'active',
    },
    {
        id: '89',
        firstName: 'Aman',
        lastName: 'Dev Burman',
        email: 'amanburman@gmail.com',
        phone: '9874563214',
        status: 'active',
    },
    {
        id: '98',
        firstName: 'Mano',
        lastName: 'Pan',
        email: 'manopan@gmail.com',
        phone: '7845123654',
        status: 'inactive',
    },
    {
        id: '87',
        firstName: 'Preetam',
        lastName: 'Kumar',
        email: 'preetamKumar@gmail.com',
        phone: '9568748596',
        status: 'active',
    }
];